# _config.yml for GitHub Pages with MathJax

# Basic settings
title: CS 180 Portfolio
url: "https://ltcyb.github.io"
baseurl: "/cs-180-portfolio"

# Enable GitHub Pages features
markdown: kramdown
kramdown:
  input: GFM # Use GitHub Flavored Markdown
  hard_wrap: false

# Include MathJax for LaTeX renderingåœ
plugins:
  - jekyll-seo-tag  # Optional SEO plugin
  - jekyll-feed     # Optional RSS feed plugin

usemathjax: true